### ISSUE TITLE
VTIMEZONE from Exchange Server 2010 gives TypeError: tzinfo.dst()

### ISSUE THREAD

**Issue by hrabbey** [dmedvinsky/mutt-ics#11]
When attempting to view a ICS file with VTIMEZONE with 2 timezones set, mutt-ics gives me an error:
TypeError: tzinfo.dst() must return None or timedelta, not 'bool'

I suspect this might be related to the Python icalendar module, but I do not have enough understanding to be confident.

I have a workaround, listed below, so I am now able to view calendar information in mutt.  Thank you very much!

Example problem exchange2010.ics:
```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:trimmed from Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY;LANGUAGE=en-US:Outlook invite problematic.
DTSTART;TZID=Eastern Standard Time:20150601T143000
END:VEVENT
END:VCALENDAR
```

Output of mutt-ics exchange2010.ics
```
Traceback (most recent call last):
  File "/home/hrabbey/.local/bin/mutt-ics", line 135, in <module>
    main(sys.argv)
  File "/home/hrabbey/.local/bin/mutt-ics", line 129, in main
    output = get_interesting_stuff(cal)
  File "/home/hrabbey/.local/bin/mutt-ics", line 52, in get_interesting_stuff
    c = get_component(component)
  File "/home/hrabbey/.local/bin/mutt-ics", line 65, in get_component
    return get_event(component)
  File "/home/hrabbey/.local/bin/mutt-ics", line 114, in get_event
    result = filter(bool, [get_header(e),
  File "/home/hrabbey/.local/bin/mutt-ics", line 80, in get_header
    vals.append(('DTSTART', e['DTSTART'].dt.strftime(datefmt)))
TypeError: tzinfo.dst() must return None or timedelta, not 'bool'
```

If the VTIMEZONE section is removed, the issue is not seen.
If DAYLIGHT part of VTIMEZONE is removed, the issue also goes away.
If DAYLIGHT is wrapped with its own VTIMEZONE, the issue also goes away.

Work around:
mutt-ics works on my system by changing my .mailcap to:
```
text/calendar; sed -e "/^BEGIN:VTIMEZONE/,/^END:VTIMEZONE/d" - | mutt-ics; copiousoutput
application/ics; sed -e "/^BEGIN:VTIMEZONE/,/^END:VTIMEZONE/d" - | mutt-ics; copiousoutput
```

Environment: 
Debian 7.8
mutt-ics installed by:
```
sudo apt-get install python-pip python-virtualenv
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
pipsi install mutt_ics
```

**Comment by dmedvinsky** [comment]
Seems like an issue after icalendar update, because I couldn't reproduce it with icalendar==3.8.4 but was able to with icalendar==3.9.0.

**Comment by j-valdes** [comment]
I've encountered this exact problem also when using icalendar 3.9.0 to view events generated by Exchange 2010. The issue seems to be triggered by the fact that the day given by the date-time value for DTSTART doesn't match a day given by the RRULE in each of the STANDARD and DAYLIGHT sub-components of the VTIMEZONE component. In the OP's example, DTSTART in both sub-components is set to 16010101T020000, Jan 1, 1601, which was a Thursday, but the RRULE in the STANDARD sub-component indicates that the switch to standard time happens on the 1st Sunday of November (BYDAY=1SU;BYMONTH=11) while the RRULE in the DAYLIGHT sub-component indicates that the switch to daylight time happens on the 2nd Sunday of March (BYDAY=2SU;BYMONTH=3), neither of which is a Thu in Jan. If the DTSTART value in each sub-component is changed to a date that matches the corresponding RRULE, eg, to DTSTART:20071104T020000 (Sun, Nov 4, 2007) for STANDARD and DTSTART:20070311T020000 (Sun, Mar 11, 2007) for DAYLIGHT, then icalendar properly parses (and presumedly uses) the timezone dst rules.

I'm not sure where the bug lies here (with Exchange for setting incorrect DTSTART date-times or icalendar for not being more lax when combining DTSTART values with RRULEs in VTIMEZONE--from my quick read of RFC 2445 and in particular section 4.8.5.4, the DTSTART value should/must indicate (ie, match) the first instance of a recurrence rule--but if one doesn't want to strip out the VTIMEZONE section of an event in the ICS file, another workaround is to correct the DTSTART values in VTIMEZONE to match the RRULEs. Since this bug isn't in mutt-ics, in principle it is best fixed/worked-around outside of mutt-ics (eg, using a pipeline in one's .mailcap like the OP did). However, since mutt-ics already has a workaround in get_ics_text() for Exchange events, that can be easily expanded to:

    --- mutt-ics.dist	2015-07-03 12:10:00.000000000 -0500
    +++ mutt-ics	2015-07-03 14:37:24.000000000 -0500
    @@ -42,7 +42,8 @@
         # Ugly workaround: Python datetime doesn't support dates earlier than 1900,
         # whilst Microsoft corp. has created it's Exchange Sever 2007 somewhere in
         # the beginning of XVII century. Yeah, right.
    -    ics_text = content.replace("\nDTSTART:1601", "\nDTSTART:1901")
    +    ics_text = content.replace("STANDARD\nDTSTART:16010101", "STANDARD\nDTSTART:20071104")
    +    ics_text = content.replace("DAYLIGHT\nDTSTART:16010101", "DAYLIGHT\nDTSTART:20070311")
         return ics_text
     
     
at least for US timezones. A more general workaround for any timezone would probably require parsing the RRULE and figuring out which dates in the current year match an instance of the RRULE.

**Comment by dmedvinsky** [comment]
Even though nobody likes workarounds, I'm being pragmatic here and included your fix. Thanks @j-valdes!
